---
# role: ansible-role-ssh
# file: tasks/setup.yml

- name: "Install ssh client packages"
  package:
    name: "{{ ssh_package }}"
    state: present
  loop: "{{ ssh_packages }}"
  loop_control:
    loop_var: ssh_package
  when: ssh_enabled | bool
    or sshd_enabled | bool

- name: "Install ssh server packages"
  package:
    name: "{{ sshd_package }}"
    state: present
  loop: "{{ sshd_packages }}"
  loop_control:
    loop_var: sshd_package
  when: sshd_enabled | bool

- name: "Determine ssh version"
  shell: set -o pipefail && ssh -V 2>&1 | sed -r "s/.*_([0-9.]*).*\s{1}.*/\1/"
  args:
    executable: /bin/bash
  changed_when: False
  register: ssh_version_out
  check_mode: no

- name: "Set fact ssh_version"
  set_fact:
    ssh_version: "{{ ssh_version_out.stdout }}"

- name: "Print openssh version"
  debug:
    msg: "ssh version: {{ ssh_version }}"

# binutils are needed below ssh 6.3, because -Q option is not available.
- name: "Install binutils for algorithm extraction"
  package:
    name: "{{ ssh_binutils_package }}"
    state: present
  when: ssh_version is version("{{ ssh_q_version }}", '<')

- name: "Check if {{ sshd_moduli_file }} contains weak DH parameters"
  shell: awk '$5 < {{ sshd_moduli_minimum }}' {{ sshd_moduli_file }}
  register: sshd_register_moduli
  changed_when: false
  check_mode: no

- name: "Remove primes smaller than {{ sshd_moduli_minimum }}"
  shell: |
    awk '$5 >= {{ sshd_moduli_minimum }}' {{ sshd_moduli_file }} > \
    {{ sshd_moduli_file }}.new
    [ -f {{ sshd_moduli_file }}.new ] && \
    mv {{ sshd_moduli_file }}.new {{ sshd_moduli_file }} || true
  when: sshd_register_moduli.stdout
