---
# role: ansible-role-ssh
# file: tasks/sshd.yml

# - name: Start sshd
#   service:
#     name: "{{ sshd_service_name }}"
#     state: started

- name: Inlcude local pubkey from current user in remote users authorized_keys
  become: false
  authorized_key:
    user: "{{ ansible_user | default(ansible_user_id, True) }}"
    state: present
    key: "{{ lookup('file', ssh_deploy_key) }}"
  when: ssh_deploy_key | length > 0
    and sshd_pubkey_auth | bool

- name: Set up etc/ssh/shosts.equiv
  template:
    src: 'etc/ssh/shosts.equiv.j2'
    dest: '/etc/ssh/shosts.equiv'
    mode: '0600'
    owner: 'root'
    group: 'root'
  when: sshd_hostbased_auth | bool

- name: Set up etc/ssh/ssh_known_hosts
  known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: "{{ item.key }}"
    key: "{{ item.value }}"
    state: present
    hash_host: yes
  loop: "{{ sshd_ssh_known_hosts | dict2items }}"

- name: Set up sshd configuration in /etc/ssh/sshd_config
  template:
    src: 'etc/ssh/sshd_config.j2'
    dest: '/etc/ssh/sshd_config'
    mode: '0600'
    owner: 'root'
    group: 'root'
    backup: "{{ sshd_conf_backup }}"
    validate: '/usr/sbin/sshd -T -C user=root -C host=localhost -C addr=localhost -f %s'
  notify: restart sshd
