---
# role: ansible-role-ssh
# file: tasks/tasks.yml

- name: Set os_family dependent variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Set distribution dependent variables
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  loop_control:
    loop_var: vars_file

# - name: Include tasks for installing openssh
#   include_tasks: setup.yml

# - name: Include tasks for setting up host keys
#   include_tasks: hostkeys.yml
#   loop: "{{ sshd_host_keys }}"
#   loop_control:
#     loop_var: hostkey

- name: Include tasks for setting version related algorithm facts
  include_tasks: version.yml

# - name: Include tasks for setting up ssh
#   include_tasks: ssh.yml
#   when: ssh_enabled | bool

- name: Include tasks for setting up sshd
  include_tasks: sshd.yml
  when: sshd_enabled | bool

# - name: Enable/Disable sshd according to sshd_enabled
#   service:
#     name: "{{ sshd_service_name }}"
#     enabled: "{{ sshd_enabled | bool }}"

- name: Debug ssh version
  debug:
    msg: "{{ ssh_version.stdout }}"
